core/urls.py
from django.conf.urls import url
from core.views import Receipts_Deposit, ClientLoanAccountsView, GetLoanDemandsView, PaySlipCreateView, get_group_loan_accounts, \
	get_member_loan_accounts, GetFixedDepositAccountsView, GetRecurringDepositAccountsView, ClientDepositAccountsView, \
	GetFixedDepositPaidAccountsView, GetRecurringDepositPaidAccountsView

urlpatterns = [
    url(r'^receiptsdeposit/$', Receipts_Deposit.as_view(), name="receiptsdeposit"),
    url(r'^getmemberloanaccounts/$', ClientLoanAccountsView.as_view(), name="receiptsdeposit"),
    url(r'^getloandemands/$', GetLoanDemandsView.as_view(), name="getloandemands"),
    url(r'^payslip/$', PaySlipCreateView.as_view(), name="payslip"),
    url(r'^loanaccounts/group$', get_group_loan_accounts, name="get_group_loan_accounts"),
    url(r'^loanaccounts/member$', get_member_loan_accounts, name="get_member_loan_accounts"),
    url(r'^getmemberfixeddepositaccounts/$', GetFixedDepositAccountsView.as_view(), name="getmemberfixeddepositaccounts"),
    url(r'^getmemberrecurringdepositaccounts/$', GetRecurringDepositAccountsView.as_view(), name="getmemberrecurringdepositaccounts"),
    url(r'^getmemberdepositaccounts/$', ClientDepositAccountsView.as_view(), name="getmemberdepositaccounts"),
    url(r'^getmemberfixeddepositpaidaccounts/$', GetFixedDepositPaidAccountsView.as_view(), name="getmemberfixeddepositpaidaccounts"),
    url(r'^getmemberrecurringdepositpaidaccounts/$', GetRecurringDepositPaidAccountsView.as_view(), name="getmemberrecurringdepositpaidaccounts"),
]

micro_admin/urls.py
from django.conf.urls import url
from micro_admin.views import *

urlpatterns = [

    url(r'^$', IndexView.as_view(), name='microadmin_index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    # ------------------------------------------- #
    # Branch model urls
    url(r'^branch/create/$', CreateBranchView.as_view(), name='createbranch'),
    url(r'^branch/edit/(?P<pk>\d+)/$', UpdateBranchView.as_view(), name='editbranch'),
    url(r'^branch/view/$', BranchListView.as_view(), name='viewbranch'),
    url(r'^branch/delete/(?P<pk>\d+)/$', BranchInactiveView.as_view(), name='deletebranch'),
    url(r'^branch/profile/(?P<pk>\d+)/$', BranchProfileView.as_view(), name='branchprofile'),
    # ------------------------------------------- #
    # User model urls
    url(r'^user/edit/(?P<pk>\d+)/$', UpdateUserView.as_view(), name='edituser'),
    url(r'^user/create/$', CreateUserView.as_view(), name='createuser'),
    url(r'^user/profile/(?P<pk>\d+)/$', UserProfileView.as_view(), name='userprofile'),
    url(r'^users/list/$', UsersListView.as_view(), name='userslist'),
    url(r'^user/delete/(?P<pk>\d+)/$', UserInactiveView.as_view(), name='deleteuser'),
    # ------------------------------------------- #
    # Client model urls
    url(r'^client/create/$', CreateClientView.as_view(), name='createclient'),
    url(r'^client/edit/(?P<pk>\d+)/$', UpdateClientView.as_view(), name='editclient'),
    url(r'^clients/list/$', ClientsListView.as_view(), name='viewclient'),
    url(r'^client/profile/(?P<pk>\d+)/$', ClienProfileView.as_view(), name='clientprofile'),
    url(r'^client/delete/(?P<pk>\d+)/$', ClientInactiveView.as_view(), name='deleteclient'),
    url(r'^client/profile/update/(?P<client_id>\d+)/$', update_clientprofile, name='updateclientprofile'),
    # ------------------------------------------- #
    # Group
    url(r'^group/create/$', CreateGroupView.as_view(), name='creategroup'),
    url(r'^group/(?P<group_id>\d+)/profile/$', GroupProfileView.as_view(), name='groupprofile'),
    url(r'^groups/list/$', GroupsListView.as_view(), name='groupslist'),
    url(r'^group/(?P<group_id>\d+)/delete/$', GroupInactiveView.as_view(), name='deletegroup'),

    # Group - Assign Staff
    url(r'^group/(?P<group_id>\d+)/assign-staff/$', GroupAssignStaffView.as_view(), name='assignstaff'),

    # Group Members (add, remove, view)
    url(r'^group/(?P<group_id>\d+)/members/add/$', GroupAddMembersView.as_view(), name='addmember'),
    url(r'^group/(?P<group_id>\d+)/members/list/$', GroupMembersListView.as_view(), name='viewmembers'),
    url(r'^group/(?P<group_id>\d+)/member/(?P<client_id>\d+)/remove/$', GroupRemoveMembersView.as_view(), name='removemember'),

    # Group Meeting (list, add)
    url(r'^group/(?P<group_id>\d+)/meetings/list/$', GroupMeetingsListView.as_view(), name='groupmeetings'),
    url(r'^group/(?P<group_id>\d+)/meetings/add/$', GroupMeetingsAddView.as_view(), name='addgroupmeeting'),

    # Receipts(create, list)
    url(r'^receiptsdeposit/$', receipts_deposit, name="receiptsdeposit"),
    url(r'^receiptslist/$', ReceiptsList.as_view(), name="receiptslist"),

    url(r'^generalledger/$', GeneralLedger.as_view(), name="generalledger"),
    url(r'^fixeddeposits/$', FixedDepositsView.as_view(), name="fixeddeposits"),
    url(r'^clientfixeddepositsprofile/(?P<fixed_deposit_id>\d+)/$', ClientFixedDepositsProfile.as_view(), name="clientfixeddepositsprofile"),
    url(r'^viewclientfixeddeposits/$', ViewClientFixedDeposits.as_view(), name="viewclientfixeddeposits"),

    # Day Book
    url(r'^viewdaybook/$', DayBookView.as_view(), name="viewdaybook"),
    url(r'^viewparticularclientfixeddeposits/(?P<client_id>\d+)/$', ViewParticularClientFixedDeposits.as_view(), name="viewparticularclientfixeddeposits"),
    url(r'^payslip/$', pay_slip, name="payslip"),
    url(r'^paymentslist/$', PaymentsList.as_view(), name="paymentslist"),
    url(r'^recurringdeposits/$', RecurringDepositsView.as_view(), name="recurringdeposits"),
    url(r'^clientrecurringdepositsprofile/(?P<recurring_deposit_id>\d+)/$', ClientRecurringDepositsProfile.as_view(), name="clientrecurringdepositsprofile"),
    url(r'^viewclientrecurringdeposits/$', ViewClientRecurringDeposits.as_view(), name="viewclientrecurringdeposits"),
    url(r'^viewparticularclientrecurringdeposits/(?P<client_id>\d+)/$', ViewParticularClientRecurringDeposits.as_view(), name="viewparticularclientrecurringdeposits"),
    url(r'^generalledgerpdfdownload/$', GeneralLedgerPdfDownload.as_view(), name="generalledgerpdfdownload"),
    url(r'^daybookpdfdownload/(?P<date>\d{4}-\d{2}-\d{2})/$', DayBookPdfDownload.as_view(), name="daybookpdfdownload"),
    url(r'^userchangepassword/$', UserChangePassword.as_view(), name="userchangepassword"),
    url(r'^getmemberloanaccounts/$', getmember_loanaccounts, name="getmemberloanaccounts"),
    url(r'^getloandemands/$', getloan_demands, name="getloandemands"),
]

microfinance/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^', include('micro_admin.urls', namespace='micro_admin')),
    url(r'^', include('savings.urls', namespace='savings')),
    url(r'^', include('loans.urls', namespace='loans')),
    url(r'^finance/', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

savings/urls.py
from django.conf.urls import url
from savings.views import *

urlpatterns = [
    # Client Savings
    url(r'^client/(?P<client_id>\d+)/savings/application/$', ClientSavingsApplicationView.as_view(), name='clientsavingsapplication'),
    url(r'^client/(?P<client_id>\d+)/savings/account/view/$', ClientSavingsAccountView.as_view(), name='clientsavingsaccount'),
    url(r'^client/(?P<client_id>\d+)/savings/deposits/list/$', ClientSavingsDepositsListView.as_view(), name='listofclientsavingsdeposits'),
    url(r'^client/(?P<client_id>\d+)/savings/withdrawals/list/$', ClientSavingsWithdrawalsListView.as_view(), name='listofclientsavingswithdrawals'),

    # Group Savings
    url(r'^group/(?P<group_id>\d+)/savings/application/$', GroupSavingsApplicationView.as_view(), name='groupsavingsapplication'),
    url(r'^group/(?P<group_id>\d+)/savings/account/view/$', GroupSavingsAccountView.as_view(), name='groupsavingsaccount'),
    url(r'^group/(?P<group_id>\d+)/savings/deposits/list/$', GroupSavingsDepositsListView.as_view(), name='viewgroupsavingsdeposits'),
    url(r'^group/(?P<group_id>\d+)/savings/withdrawals/list/$', GroupSavingsWithdrawalsListView.as_view(), name='viewgroupsavingswithdrawals'),

    # Change Savings Account Status
    url(r'^savings/account/(?P<savingsaccount_id>\d+)/change-status/$', ChangeSavingsAccountStatus.as_view(),
        name='change-savings-account-status'),
]

savings/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.views.generic import CreateView, UpdateView, DetailView, ListView
from micro_admin.models import Group, Client, SavingsAccount, Receipts, Payments
from micro_admin.forms import SavingsAccountForm
from django.db.models import Sum
import decimal
import datetime

d = decimal.Decimal


# Client Savings
class ClientSavingsApplicationView(LoginRequiredMixin, CreateView):
    model = SavingsAccount
    form_class = SavingsAccountForm
    template_name = "client/savings/application.html"

    def dispatch(self, request, *args, **kwargs):
        self.client = get_object_or_404(Client, id=self.kwargs.get('client_id'))
        if SavingsAccount.objects.filter(client=self.client).exists():
            return HttpResponseRedirect(reverse("savings:clientsavingsaccount",
                                                kwargs={'client_id': self.client.id}))
        return super(ClientSavingsApplicationView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ClientSavingsApplicationView, self).get_context_data(**kwargs)
        count = SavingsAccount.objects.all().count()
        context["client"] = self.client
        context["account_no"] = "%s%s%d" % ("S", self.client.branch.id, count + 1)
        return context

    def form_valid(self, form):
        obj_sav_acc = form.save(commit=False)
        obj_sav_acc.status = "Applied"
        obj_sav_acc.created_by = self.request.user
        obj_sav_acc.client = self.client
        obj_sav_acc.save()
        return JsonResponse({"error": False, "client_id": self.client.id})

    def form_invalid(self, form):
        return JsonResponse({"error": True, "errors": form.errors})


class ClientSavingsAccountView(LoginRequiredMixin, DetailView):
    model = SavingsAccount
    context_object_name = "savingsaccount"
    template_name = "client/savings/account.html"

    def get_object(self):
        self.client = get_object_or_404(Client, id=self.kwargs.get("client_id"))
        self.object = get_object_or_404(SavingsAccount, client=self.client)
        return self.object

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context["client"] = self.client
        return self.render_to_response(context)


class ClientSavingsDepositsListView(LoginRequiredMixin, ListView):
    model = Receipts
    context_object_name = "receipts_lists"
    template_name = "client/savings/list_of_savings_deposits.html"

    def get_queryset(self):
        queryset = self.model.objects.filter(
            client=self.kwargs.get('client_id')
        ).exclude(savingsdeposit_thrift_amount=0)
        return queryset

    def get_context_data(self):
        context = super(ClientSavingsDepositsListView, self).get_context_data()
        context["savingsaccount"] = get_object_or_404(SavingsAccount, client=self.kwargs.get("client_id"))
        return context


class ClientSavingsWithdrawalsListView(LoginRequiredMixin, ListView):
    model = Payments
    context_object_name = "savings_withdrawals_list"
    template_name = "client/savings/list_of_savings_withdrawals.html"

    def get_queryset(self):
        self.client = get_object_or_404(Client, id=self.kwargs.get("client_id"))
        queryset = self.model.objects.filter(
            client=self.client,
            payment_type="SavingsWithdrawal"
        )
        return queryset

    def get_context_data(self):
        context = super(ClientSavingsWithdrawalsListView, self).get_context_data()
        context['client'] = self.client
        return context


# Group Savings
class GroupSavingsApplicationView(LoginRequiredMixin, CreateView):
    model = SavingsAccount
    form_class = SavingsAccountForm
    template_name = "group/savings/application.html"

    def dispatch(self, request, *args, **kwargs):
        self.group = get_object_or_404(Group, id=self.kwargs.get('group_id'))
        if SavingsAccount.objects.filter(group=self.group).exists():
            return HttpResponseRedirect(
                reverse("savings:groupsavingsaccount",
                        kwargs={'group_id': self.group.id})
            )
        return super(GroupSavingsApplicationView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GroupSavingsApplicationView, self).get_context_data(**kwargs)
        count = SavingsAccount.objects.all().count()
        context["group"] = self.group
        context["account_no"] = "%s%s%d" % ("S", self.group.branch.id, count + 1)
        return context

    def form_valid(self, form):
        obj_sav_acc = form.save(commit=False)
        obj_sav_acc.status = "Applied"
        obj_sav_acc.created_by = self.request.user
        obj_sav_acc.group = self.group
        obj_sav_acc.save()
        return JsonResponse({
            "error": False,
            "success_url": reverse("savings:groupsavingsaccount",
                                   kwargs={'group_id': self.group.id})
        })

    def form_invalid(self, form):
        return JsonResponse({"error": True, "errors": form.errors})


class GroupSavingsAccountView(LoginRequiredMixin, DetailView):
    model = SavingsAccount
    context_object_name = "savings_account"
    pk_url_kwarg = "group_id"
    template_name = "group/savings/account.html"

    def get_object(self):
        self.group = get_object_or_404(Group, id=self.kwargs.get("group_id"))
        self.object = get_object_or_404(SavingsAccount, group=self.group)
        return self.object

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context["group"] = self.group
        context["totals"] = self.group.clients.all().aggregate(
            sharecapital_amount=Sum('sharecapital_amount'),
            entrancefee_amount=Sum('entrancefee_amount'),
            membershipfee_amount=Sum('membershipfee_amount'),
            bookfee_amount=Sum('bookfee_amount'),
            insurance_amount=Sum('insurance_amount'),
        )
        return self.render_to_response(context)


class GroupSavingsDepositsListView(LoginRequiredMixin, ListView):
    model = Receipts
    context_object_name = "receipts_list"
    template_name = "group/savings/list_of_savings_deposits.html"

    def get_queryset(self):
        self.group = get_object_or_404(Group, id=self.kwargs.get("group_id"))
        self.savings_account = get_object_or_404(SavingsAccount, group=self.group)
        queryset = self.model.objects.filter(
            group=self.group
        ).exclude(
            savingsdeposit_thrift_amount=0
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(GroupSavingsDepositsListView, self).get_context_data(**kwargs)
        context["savings_account"] = self.savings_account
        context["group"] = self.group
        return context


class GroupSavingsWithdrawalsListView(LoginRequiredMixin, ListView):
    model = Payments
    context_object_name = "savings_withdrawals_list"
    template_name = "group/savings/list_of_savings_withdrawals.html"

    def get_queryset(self):
        self.group = get_object_or_404(Group, id=self.kwargs.get("group_id"))
        queryset = self.model.objects.filter(
            group=self.group,
            payment_type="SavingsWithdrawal"
        )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(GroupSavingsWithdrawalsListView, self).get_context_data(**kwargs)
        context["group"] = self.group
        return context


# Change Group/Client Savings account status
class ChangeSavingsAccountStatus(LoginRequiredMixin, UpdateView):
    model = SavingsAccount
    pk_url_kwarg = "savingsaccount_id"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        group = self.object.group
        client = self.object.client
        if group:
            branch_id = group.branch.id
        elif client:
            branch_id = client.branch.id
        else:
            branch_id = None
        if branch_id:
            if (
                request.user.is_admin or
                (request.user.has_perm("branch_manager") and request.user.branch.id == branch_id)
            ):
                if request.POST.get("status") in ['Closed', 'Withdrawn', 'Rejected', 'Approved']:
                    self.object.status = request.POST.get("status")
                    self.object.approved_date = datetime.datetime.now()
                    self.object.save()
                    data = {"error": False}
                else:
                    data = {"error": True,
                            "error_message": "Invalid status. Selected status is not in available choices."}
            else:
                data = {
                    "error": True,
                    "error_message": "You don't have permission to change the status.",
                }
        else:
            data = {"error": True, "error_message": "Branch ID not Found"}
        return JsonResponse(data)

templates/client/savings/account.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li><a href="{% url 'micro_admin:branchprofile' client.branch.id %}">{{ client.branch.name|capfirst }} Branch</a></li>
<li><a href="{% url 'micro_admin:clientprofile' client.id %}">{{ client.first_name|capfirst }} Member</a></li>
<li>Savings Account</li>
{% endblock %}
{% block stage %}
<!--content goes below-->
<div class="container">
  <div class="wrap-cp-div btn-usa-div margin-top-set mar-wid-12">
    <div class="btn-row" >
      {% if user.is_admin or user.user_roles == "BranchManager" %}
      {% if savingsaccount.status == "Approved" %}
        <button title="Already Approved"><i class="fa fa-check-circle-o padd"></i>Approved</button>
      {% else %}
        <button class="change-account-status" data-href="Approved"><i class="fa fa-check-circle-o padd"></i>Approve</button>
      {% endif %}
      {% if savingsaccount.status == "Withdrawn" %}
        <button title="Already Withrawn"><i class="fa fa-arrow-circle-o-down padd"></i>Withdrawn</button>
      {% else %}
        <button class="change-account-status" data-href="Withdrawn"><i class="fa fa-arrow-circle-o-down padd"></i>Withdraw</button>
      {% endif %}
      {% if savingsaccount.status == "Rejected" %}
        <button title="Already Rejected"><i class="fa fa-times-circle-o padd"></i>Rejected</button>
      {% else %}
        <button class="change-account-status" data-href="Rejected"><i class="fa fa-times-circle-o padd"></i>Reject</button>
      {% endif %}
      {% if savingsaccount.status == "Closed" %}
        <button title="Already Closed"><i class="fa fa-trash-o padd"></i>Closed</button>
      {% else %}
        <button class="change-account-status" data-href="Closed"><i class="fa fa-trash-o padd"></i>Close</button>
      {% endif %}
      <br clear="all" />
      {% endif %}
    </div>
  </div>
  <!--form div starts below-->
  <div class="panel panel-default wrap-cp-div">
    <div class="panel-heading min-ht-res-60">
      <h3 class="panel-title">
        {% if client.is_active %}
        <i class="fa fa-square green padd"></i>
        {% else %}
        <i class="fa fa-square red padd"></i>{% endif %}
        {{ client.first_name|capfirst }} Savings Account</h3>
        <span class="mar-tp-m mar-tp-m24">
        <a href="{% url 'savings:listofclientsavingswithdrawals' client.id %}" class="view-tab-btn"><i class="fa fa-eye padd"></i>View Savings Withdrawals</a>
        <a href="{% url 'savings:listofclientsavingsdeposits' client.id %}" class="view-tab-btn"><i class="fa fa-eye padd"></i>View Savings Deposits</a>
        {% if user.is_admin == 0 and user.user_roles != "BranchManager" %}
          {% if savingsaccount.status == "Withdrawn" %}
            <a title="Already Withrawn" class="view-tab-btn"><i class="fa fa-arrow-circle-o-down padd"></i>Withdrawn</a>
          {% else %}
            <a data-href="Withdrawn" class="view-tab-btn change-account-status"><i class="fa fa-arrow-circle-o-down padd"></i>Withdraw</a>
          {% endif %}
        {% endif %}
        </span>
    </div>
    <div class="panel-body pb-pad">
      <form id="clientsavingsaccountform"  class="form-horizontal" role="form" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-6 col-xs-6 control-label">Account Number</label>
          <div class="col-sm-6 col-xs-6">
            <label for="inputEmail3" class="control-label">{{ savingsaccount.account_no }}</label>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-6 col-xs-6 control-label">Applied By Staff</label>
          <div class="col-sm-6 col-xs-6">
            <label for="inputEmail3" class="control-label">
            <a href="{% url 'micro_admin:userprofile' savingsaccount.created_by.id %}">
            {{ savingsaccount.created_by|capfirst }}</a>
            </label>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-6 col-xs-6 control-label">Savings Balance</label>
          <div class="col-sm-6 col-xs-6">
            <label for="inputEmail3" class="control-label">{{ savingsaccount.savings_balance|floatformat:2 }}</label>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-6 col-xs-6 control-label">Activation date</label>
          <div class="col-sm-6 col-xs-6">
            <label for="inputEmail3" class="control-label">{{ savingsaccount.opening_date }}</label>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-6 col-xs-6 control-label">Status</label>
          <div class="col-sm-6 col-xs-6">
            {% if savingsaccount.status == "Applied" %}
            <label for="inputEmail3" class="control-label" style="color:#337ab7;">
            {% elif savingsaccount.status == "Withdrawn" %}
            <label for="inputEmail3" class="control-label" style="color:#FF6600;">
            {% elif savingsaccount.status == "Approved" %}
            <label for="inputEmail3" class="control-label" style="color:#008000;">
            {% elif savingsaccount.status == "Rejected" %}
            <label for="inputEmail3" class="control-label red">
            {% elif savingsaccount.status == "Closed" %}
            <label for="inputEmail3" class="control-label" style="color:#660099;">
            {% endif %}
            {{ savingsaccount.status }}
            </label>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-6 col-xs-6 control-label">Annual Interest Rate</label>
          <div class="col-sm-6 col-xs-6">
            <label for="inputEmail3" class="control-label">{{ savingsaccount.annual_interest_rate }} %</label>
          </div>
        </div>
      </form>
    </div>
  </div>
  <!--form div ends above-->
</div>
<!--wrapper ends above-->
<script type="text/javascript">
  $(document).ready(function() {
    $('.change-account-status').click(function(e) {
      e.preventDefault();
      var submit_url = "{% url 'savings:change-savings-account-status' savingsaccount.id %}"
      $.post(submit_url, {"status": $(this).attr("data-href"), "csrfmiddlewaretoken": $("input[name='csrfmiddlewaretoken']").val() }, function(data) {
        if (data.error) {
          alert(data.error_message);
        }
        else {
          alert("Member savings account status changed successfully");
          window.location = '.';
        }
      }, "json");
    });
  });
</script>
{% endblock %}

templates/client/savings/application.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li><a href="{% url 'micro_admin:branchprofile' client.branch.id %}">{{ client.branch.name|capfirst }} Branch</a></li>
<li><a href="{% url 'micro_admin:clientprofile' client.id %}">{{ client.first_name|capfirst }} Member</a></li>
<li>Add Savings Application</li>
{% endblock %}
{% block stage %}
<!--content goes below-->
<div class="container">
  <!--form div starts below-->
  <div class="panel panel-default my-panel margin-top-set">
    <div class="panel-heading">
    {% if client.is_active %}
     <i class="fa fa-square green padd"></i>{% else %}<i class="fa fa-square red padd"></i>{% endif %}
    {{client.first_name|capfirst}} Savings Application</div>
    <div class="panel-body pb-pad">
      <form id="clientsavingsapplicationform" class="form-horizontal" role="form" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-4 control-label">Savings A/C. No.</label>
          <div class="col-sm-8">
            <input type="hidden"  id="client_id" value="{{client.id}}" style="dispaly:none;">
            <input type="text" class="text-box wid-form" name="account_no" value="{{ account_no }}" id="account_no">
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-4 control-label">Created By</label>
          <div class="col-sm-8">
            <input type="text" class="text-box wid-form" value="{{ user.username }}" id="created_by">
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-4 control-label">Opening Date<span>*</span></label>
          <div class="col-sm-8">
            <input type="text" class="text-box wid-form" name="opening_date" id="date-picker-cc">
            <p id="opening_date"></p>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-4 control-label">Minimum Balance<span>*</span></label>
          <div class="col-sm-8">
            <input type="text" class="text-box wid-form" name="min_required_balance" id="min_required_balance">
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-4 control-label">Annual Interest Rate<span>*</span></label>
          <div class="col-sm-8">
            <input type="text" class="text-box wid-form" name="annual_interest_rate" id="annual_interest_rate">
          </div>
        </div>
        <div class="form-group btns">
          <button class="submit-btn" type="submit"><i class="fa fa-check padd"></i>Submit</button>
          <button class="cancel-btn" type="reset"><i class="fa fa-times padd"></i>Cancel</button>
        </div>
      </form>
    </div>
  </div>
  <!--form div ends above-->
</div>
<!--content ends above-->
<script type="text/javascript">
  $(document).ready(function() {
    $('#clientsavingsapplicationform').submit(function(e) {
      e.preventDefault();
      $.post('.', $('#clientsavingsapplicationform').serialize(), function(data) {
        if (data.error) {
          $("span.error").remove();
          $.each(data.errors, function( key, value ) {
            $('#'+key).after("<span class='error' style='height:11px;color:red;'>" + value + "</span>");
          });
        }
        else {
          url = "{% url 'savings:clientsavingsaccount' 1 %}".replace(1, data.client_id)
          window.location = url;
        }
      }, "json");
    });
    $('.cancel-btn').click(function(e){
      $("span.error").remove();
    });
  });
</script>
{% endblock %}