core/urls.py
from django.conf.urls import url
from core.views import Receipts_Deposit, ClientLoanAccountsView, GetLoanDemandsView, PaySlipCreateView, get_group_loan_accounts, \
	get_member_loan_accounts, GetFixedDepositAccountsView, GetRecurringDepositAccountsView, ClientDepositAccountsView, \
	GetFixedDepositPaidAccountsView, GetRecurringDepositPaidAccountsView

urlpatterns = [
    url(r'^receiptsdeposit/$', Receipts_Deposit.as_view(), name="receiptsdeposit"),
    url(r'^getmemberloanaccounts/$', ClientLoanAccountsView.as_view(), name="receiptsdeposit"),
    url(r'^getloandemands/$', GetLoanDemandsView.as_view(), name="getloandemands"),
    url(r'^payslip/$', PaySlipCreateView.as_view(), name="payslip"),
    url(r'^loanaccounts/group$', get_group_loan_accounts, name="get_group_loan_accounts"),
    url(r'^loanaccounts/member$', get_member_loan_accounts, name="get_member_loan_accounts"),
    url(r'^getmemberfixeddepositaccounts/$', GetFixedDepositAccountsView.as_view(), name="getmemberfixeddepositaccounts"),
    url(r'^getmemberrecurringdepositaccounts/$', GetRecurringDepositAccountsView.as_view(), name="getmemberrecurringdepositaccounts"),
    url(r'^getmemberdepositaccounts/$', ClientDepositAccountsView.as_view(), name="getmemberdepositaccounts"),
    url(r'^getmemberfixeddepositpaidaccounts/$', GetFixedDepositPaidAccountsView.as_view(), name="getmemberfixeddepositpaidaccounts"),
    url(r'^getmemberrecurringdepositpaidaccounts/$', GetRecurringDepositPaidAccountsView.as_view(), name="getmemberrecurringdepositpaidaccounts"),
]

loans/urls.py
from django.conf.urls import url
from loans.views import *

urlpatterns = [
    # Client Loans (apply, view, list)
    url(r'^client/(?P<client_id>\d+)/loan/apply/$', ClientLoanApplicationView.as_view(), name='clientloanapplication'),
    url(r'^client/(?P<client_id>\d+)/loans/list/$', ClientLoansListView.as_view(), name="clientloanaccountslist"),
    url(r'^client/loan/(?P<pk>\d+)/view/$', ClientLoanAccount.as_view(), name='clientloanaccount'),
    url(r'^client/(?P<client_id>\d+)/loan/(?P<loanaccount_id>\d+)/deposits/list/$', ClientLoanDepositsListView.as_view(), name='listofclientloandeposits'),

    # Client Loans - Ledger (view, CSV, Excel, PDF downloads)
    url(r'^client/(?P<client_id>\d+)/loan/(?P<loanaccount_id>\d+)/ledger/$', ClientLoanLedgerView.as_view(), name="clientloanledgeraccount"),
    url(r'^client/(?P<client_id>\d+)/loan/(?P<loanaccount_id>\d+)/ledger/download/csv/$', ClientLedgerCSVDownload.as_view(), name="clientledgercsvdownload"),
    url(r'^client/(?P<client_id>\d+)/loan/(?P<loanaccount_id>\d+)/ledger/download/excel/$', ClientLedgerExcelDownload.as_view(), name="clientledgerexceldownload"),
    url(r'^client/(?P<client_id>\d+)/loan/(?P<loanaccount_id>\d+)/ledger/download/pdf/$', ClientLedgerPDFDownload.as_view(), name="clientledgerpdfdownload"),

    # Group Loans (apply, view, list)
    url(r'^group/(?P<group_id>\d+)/loan/apply/$', GroupLoanApplicationView.as_view(), name='grouploanapplication'),
    url(r'^group/(?P<group_id>\d+)/loans/list/$', GroupLoansListView.as_view(), name="grouploanaccountslist"),
    url(r'^group/loan/(?P<pk>\d+)/view/$', GroupLoanAccount.as_view(), name='grouploanaccount'),
    url(r'^group/(?P<group_id>\d+)/loan/(?P<loanaccount_id>\d+)/deposits/list/$', GroupLoanDepositsListView.as_view(), name='viewgrouploandeposits'),

    # Change Loan Account Status
    url(r'^loan/(?P<pk>\d+)/change-status/$', ChangeLoanAccountStatus.as_view(), name='change_loan_account_status'),

    # Issue Loan
    url(r'^loan/(?P<loanaccount_id>\d+)/issue/$', IssueLoan.as_view(), name='issueloan'),
]

micro_admin/urls.py
from django.conf.urls import url
from micro_admin.views import *

urlpatterns = [

    url(r'^$', IndexView.as_view(), name='microadmin_index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    # ------------------------------------------- #
    # Branch model urls
    url(r'^branch/create/$', CreateBranchView.as_view(), name='createbranch'),
    url(r'^branch/edit/(?P<pk>\d+)/$', UpdateBranchView.as_view(), name='editbranch'),
    url(r'^branch/view/$', BranchListView.as_view(), name='viewbranch'),
    url(r'^branch/delete/(?P<pk>\d+)/$', BranchInactiveView.as_view(), name='deletebranch'),
    url(r'^branch/profile/(?P<pk>\d+)/$', BranchProfileView.as_view(), name='branchprofile'),
    # ------------------------------------------- #
    # User model urls
    url(r'^user/edit/(?P<pk>\d+)/$', UpdateUserView.as_view(), name='edituser'),
    url(r'^user/create/$', CreateUserView.as_view(), name='createuser'),
    url(r'^user/profile/(?P<pk>\d+)/$', UserProfileView.as_view(), name='userprofile'),
    url(r'^users/list/$', UsersListView.as_view(), name='userslist'),
    url(r'^user/delete/(?P<pk>\d+)/$', UserInactiveView.as_view(), name='deleteuser'),
    # ------------------------------------------- #
    # Client model urls
    url(r'^client/create/$', CreateClientView.as_view(), name='createclient'),
    url(r'^client/edit/(?P<pk>\d+)/$', UpdateClientView.as_view(), name='editclient'),
    url(r'^clients/list/$', ClientsListView.as_view(), name='viewclient'),
    url(r'^client/profile/(?P<pk>\d+)/$', ClienProfileView.as_view(), name='clientprofile'),
    url(r'^client/delete/(?P<pk>\d+)/$', ClientInactiveView.as_view(), name='deleteclient'),
    url(r'^client/profile/update/(?P<client_id>\d+)/$', update_clientprofile, name='updateclientprofile'),
    # ------------------------------------------- #
    # Group
    url(r'^group/create/$', CreateGroupView.as_view(), name='creategroup'),
    url(r'^group/(?P<group_id>\d+)/profile/$', GroupProfileView.as_view(), name='groupprofile'),
    url(r'^groups/list/$', GroupsListView.as_view(), name='groupslist'),
    url(r'^group/(?P<group_id>\d+)/delete/$', GroupInactiveView.as_view(), name='deletegroup'),

    # Group - Assign Staff
    url(r'^group/(?P<group_id>\d+)/assign-staff/$', GroupAssignStaffView.as_view(), name='assignstaff'),

    # Group Members (add, remove, view)
    url(r'^group/(?P<group_id>\d+)/members/add/$', GroupAddMembersView.as_view(), name='addmember'),
    url(r'^group/(?P<group_id>\d+)/members/list/$', GroupMembersListView.as_view(), name='viewmembers'),
    url(r'^group/(?P<group_id>\d+)/member/(?P<client_id>\d+)/remove/$', GroupRemoveMembersView.as_view(), name='removemember'),

    # Group Meeting (list, add)
    url(r'^group/(?P<group_id>\d+)/meetings/list/$', GroupMeetingsListView.as_view(), name='groupmeetings'),
    url(r'^group/(?P<group_id>\d+)/meetings/add/$', GroupMeetingsAddView.as_view(), name='addgroupmeeting'),

    # Receipts(create, list)
    url(r'^receiptsdeposit/$', receipts_deposit, name="receiptsdeposit"),
    url(r'^receiptslist/$', ReceiptsList.as_view(), name="receiptslist"),

    url(r'^generalledger/$', GeneralLedger.as_view(), name="generalledger"),
    url(r'^fixeddeposits/$', FixedDepositsView.as_view(), name="fixeddeposits"),
    url(r'^clientfixeddepositsprofile/(?P<fixed_deposit_id>\d+)/$', ClientFixedDepositsProfile.as_view(), name="clientfixeddepositsprofile"),
    url(r'^viewclientfixeddeposits/$', ViewClientFixedDeposits.as_view(), name="viewclientfixeddeposits"),

    # Day Book
    url(r'^viewdaybook/$', DayBookView.as_view(), name="viewdaybook"),
    url(r'^viewparticularclientfixeddeposits/(?P<client_id>\d+)/$', ViewParticularClientFixedDeposits.as_view(), name="viewparticularclientfixeddeposits"),
    url(r'^payslip/$', pay_slip, name="payslip"),
    url(r'^paymentslist/$', PaymentsList.as_view(), name="paymentslist"),
    url(r'^recurringdeposits/$', RecurringDepositsView.as_view(), name="recurringdeposits"),
    url(r'^clientrecurringdepositsprofile/(?P<recurring_deposit_id>\d+)/$', ClientRecurringDepositsProfile.as_view(), name="clientrecurringdepositsprofile"),
    url(r'^viewclientrecurringdeposits/$', ViewClientRecurringDeposits.as_view(), name="viewclientrecurringdeposits"),
    url(r'^viewparticularclientrecurringdeposits/(?P<client_id>\d+)/$', ViewParticularClientRecurringDeposits.as_view(), name="viewparticularclientrecurringdeposits"),
    url(r'^generalledgerpdfdownload/$', GeneralLedgerPdfDownload.as_view(), name="generalledgerpdfdownload"),
    url(r'^daybookpdfdownload/(?P<date>\d{4}-\d{2}-\d{2})/$', DayBookPdfDownload.as_view(), name="daybookpdfdownload"),
    url(r'^userchangepassword/$', UserChangePassword.as_view(), name="userchangepassword"),
    url(r'^getmemberloanaccounts/$', getmember_loanaccounts, name="getmemberloanaccounts"),
    url(r'^getloandemands/$', getloan_demands, name="getloandemands"),
]

microfinance/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^', include('micro_admin.urls', namespace='micro_admin')),
    url(r'^', include('savings.urls', namespace='savings')),
    url(r'^', include('loans.urls', namespace='loans')),
    url(r'^finance/', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

savings/urls.py
from django.conf.urls import url
from savings.views import *

urlpatterns = [
    # Client Savings
    url(r'^client/(?P<client_id>\d+)/savings/application/$', ClientSavingsApplicationView.as_view(), name='clientsavingsapplication'),
    url(r'^client/(?P<client_id>\d+)/savings/account/view/$', ClientSavingsAccountView.as_view(), name='clientsavingsaccount'),
    url(r'^client/(?P<client_id>\d+)/savings/deposits/list/$', ClientSavingsDepositsListView.as_view(), name='listofclientsavingsdeposits'),
    url(r'^client/(?P<client_id>\d+)/savings/withdrawals/list/$', ClientSavingsWithdrawalsListView.as_view(), name='listofclientsavingswithdrawals'),

    # Group Savings
    url(r'^group/(?P<group_id>\d+)/savings/application/$', GroupSavingsApplicationView.as_view(), name='groupsavingsapplication'),
    url(r'^group/(?P<group_id>\d+)/savings/account/view/$', GroupSavingsAccountView.as_view(), name='groupsavingsaccount'),
    url(r'^group/(?P<group_id>\d+)/savings/deposits/list/$', GroupSavingsDepositsListView.as_view(), name='viewgroupsavingsdeposits'),
    url(r'^group/(?P<group_id>\d+)/savings/withdrawals/list/$', GroupSavingsWithdrawalsListView.as_view(), name='viewgroupsavingswithdrawals'),

    # Change Savings Account Status
    url(r'^savings/account/(?P<savingsaccount_id>\d+)/change-status/$', ChangeSavingsAccountStatus.as_view(),
        name='change-savings-account-status'),
]

templates/client/list.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li>View Members</li>
{% endblock %}
{% block stage %}
<!--content goes below-->
<div class="container">
  <!--form div starts below-->
  <div class="panel panel-default my-panel-bprofile margin-top-set">
    <div class="panel-heading">View Members</div>
    <div class="panel-body pb-table">
      <div class="table-responsive">
        <table class="table">
          <thead>
            <tr class="head-row-tb">
              <th>Member Name</th>
              <th>Account Number</th>
              <th>Branch Name</th>
              <th>Group Name</th>
              <th>Role</th>
              <th>Status</th>
              {% if user.is_admin or user.user_roles == "BranchManager" %}
              <th>Edit/Delete</th>
              {% else %}
              <th>Edit</th>
              {% endif %}
            </tr>
          </thead>
          <tbody class="body-row-tb">
            {% for client in client_list %}
            <tr>
              <td><a href="{% url 'micro_admin:clientprofile' client.id %}" style="color:#337ab7">
              {{ client.first_name|capfirst }} {{ client.last_name|capfirst }}</a></td>
              <td>{{ client.account_number }}</td>
              <td><a href="{% url 'micro_admin:branchprofile' client.branch.id %}" style="color:#337ab7">{{ client.branch.name|capfirst}}</a></td>
              <td>
                {% if client.group_set.get %}
                  <a href="{% url 'micro_admin:groupprofile' client.group_set.get.id %}" style="color:#337ab7">
                    {{ client.group_set.get.name|capfirst}} Group </a>
                {% else %} - {% endif %}
              </td>
              <td>{{ client.client_role }}</td>
              {% if client.is_active %}
              <td><i class="fa fa-circle green pad-lt"></i></td>
              {% else %}
              <td><i class="fa fa-circle red pad-lt"></i></td>
              {% endif %}
              <td class="ed">
                <a href="{% url 'micro_admin:editclient' client.id %}"><i class="fa fa-pencil-square-o edit-icon"></i></a>
                {% if user.is_admin or user.user_roles == "BranchManager" %}
                <a href="{% url 'micro_admin:deleteclient' client.id %}"><i class="fa fa-trash-o trash-icon"></i></a>
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!--form div ends above-->
</div>
<!--content ends above-->
{% endblock %}

templates/client/profile.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li><a href="{% url 'micro_admin:branchprofile' client.branch.id %}">{{ client.branch.name|capfirst }} Branch</a></li>
<li>{{ client.first_name|capfirst }} Member</li>
{% endblock %}
{% block stage %}
<!--content goes below-->
<div class="container">
  <!--form div starts below-->
  <div class="wrap-cp-div margin-top-set">
    <div class="btn-row">
      <a href="{% url 'micro_admin:editclient' client.id %}"><button><i class="fa fa-pencil-square-o padd"></i>Edit</button></a>
      {% if client.savingsaccount_set.count %}
      <a href="{% url 'savings:clientsavingsaccount' client.id %}"><button><i class="fa fa-money padd"></i>View Savings</button></a>
      {% else %}
      <a href="{% url 'savings:clientsavingsapplication' client.id %}"><button><i class="fa fa-plus padd"></i>Savings</button></a>
      {% endif %}
      <a href="{% url 'loans:clientloanapplication' client.id %}"><button><i class="fa fa-plus padd"></i>Loan</button></a>
      <a href="{% url 'loans:clientloanaccountslist' client.id %}"><button><i class="fa fa-money padd"></i>View Loans</button></a>
      <a href="{% url 'micro_admin:viewparticularclientfixeddeposits' client.id%}"><button><i class="fa fa-eye padd"></i>Fixed Deposits</button></a>
      <a href="{% url 'micro_admin:viewparticularclientrecurringdeposits' client.id%}"><button><i class="fa fa-eye padd"></i>Recurring Deposits</button></a>
      <a href="{% url 'micro_admin:updateclientprofile' client.id %}"><button><i class="fa fa-file-image-o padd"></i>Update Profile</button></a>
      {% if user.is_admin or user.user_roles == "BranchManager" %}
      <a href="{% url 'micro_admin:deleteclient' client.id %}"><button><i class="fa fa-trash-o padd"></i>Delete</button></a>
      {% endif %}
      <br clear="all" />
    </div>
    <div class="clr-div" style ="width:100%">
      <div class="img-div">
        <h3>{{ client.last_name|capfirst }} {{ client.first_name|capfirst }}</h3>
        <img src="/{{ client.photo }}" alt="Member Photo" /><br /><br />
        <img src="/{{client.signature}}"  class="sig-div" style="" alt="Member Signature" />
        <br clear="all" />
      </div>
      <div class="details-div">
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 cl-md-6 col-sm-6 col-xs-7 control-label">Branch Name : </label>
          <a href="{% url 'micro_admin:branchprofile' client.branch.id %}">
          {{ client.branch.name|capfirst }} Branch
          </a>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Status : </label>
          {% if client.is_active %}
          <td><i class="fa fa-square icon-squa green padd"></i>Active</td>
          {% else %}
          <td><i class="fa fa-square icon-squa red padd"></i>InActive</td>
          {% endif %}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Joined Date : </label>
          {{ client.joined_date }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Group : </label>
          {% if client.group_set.get %}<a href="{% url 'micro_admin:groupprofile' client.group_set.get.id %}">
            {{ client.group_set.get.name|capfirst}} Group </a>
          {% else %} - {% endif %}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Account Number : </label>
          {{ client.account_number }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Member Role : </label>
          {{ client.client_role|capfirst }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">State : </label>
          {{ client.state|capfirst }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">District : </label>
          {{ client.district|capfirst }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Mandal : </label>
          {{ client.city|capfirst }}
        </div>
        <div class="form-group" >
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Mobile : </label>
          {{ client.mobile|default:" - " }}
        </div>

        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Share Capital Amount: </label>
          {{ client.sharecapital_amount|floatformat:2 }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Entrance Fee Amount: </label>
          {{ client.entrancefee_amount|floatformat:2 }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Membership Fee Amount: </label>
          {{ client.membershipfee_amount|floatformat:2 }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Book Fee Amount : </label>
          {{ client.bookfee_amount|floatformat:2 }}
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-5 col-md-6 col-sm-6 col-xs-7 control-label">Insurance Amount : </label>
          {{ client.insurance_amount|floatformat:2 }}
        </div>
      </div>
      <br clear="all" />
    </div>
    <!--form div ends above-->
  </div>
  <!--content ends above-->
</div>
{% endblock %}

templates/client/update-profile.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li><a href="{% url 'micro_admin:branchprofile' client.branch.id %}">{{ client.branch.name|capfirst }} Branch</a></li>
<li><a href="{% url 'micro_admin:clientprofile' client.id %}">{{ client.first_name|capfirst }} Member</a></li>
<li>Update Profile</li>
{% endblock %}
{% block stage %}
<!--content goes below-->
<div class="container">
  <!--form div starts below-->
  <div class="panel panel-default my-panel margin-top-set">
    <div class="panel-heading">{{ client.first_name|capfirst }} {{ client.last_name|capfirst }} Update Profile</div>
    <div class="panel-body pb-pad">
      <form id="updateclientprofileform" enctype="multipart/form-data" class="form-horizontal" role="form" action="{% url 'micro_admin:updateclientprofile' client.id %}" method="post" >
        {% csrf_token %}
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-4 control-label">Upload Image</label>
          <div class="col-sm-8">
            <input type="file" class="input-file-pad-top-4" accept="image/*" name="photo" />
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-4 control-label">Upload Signature</label>
          <div class="col-sm-8">
            <input type="file" class="input-file-pad-top-4" accept="image/*"  name="signature"/>
          </div>
        </div>
        <div class="form-group btns">
          <button class="submit-btn"><i class="fa fa-check padd"></i>Save</button>
          <button class="cancel-btn" type="reset"><i class="fa fa-times padd"></i>Cancel</button>
        </div>
      </form>
    </div>
  </div>
  <!--form div ends above-->
</div>
<!--content ends above-->
</div>
<!--wrapper ends above-->
{% endblock %}