core/urls.py
from django.conf.urls import url
from core.views import Receipts_Deposit, ClientLoanAccountsView, GetLoanDemandsView, PaySlipCreateView, get_group_loan_accounts, \
	get_member_loan_accounts, GetFixedDepositAccountsView, GetRecurringDepositAccountsView, ClientDepositAccountsView, \
	GetFixedDepositPaidAccountsView, GetRecurringDepositPaidAccountsView

urlpatterns = [
    url(r'^receiptsdeposit/$', Receipts_Deposit.as_view(), name="receiptsdeposit"),
    url(r'^getmemberloanaccounts/$', ClientLoanAccountsView.as_view(), name="receiptsdeposit"),
    url(r'^getloandemands/$', GetLoanDemandsView.as_view(), name="getloandemands"),
    url(r'^payslip/$', PaySlipCreateView.as_view(), name="payslip"),
    url(r'^loanaccounts/group$', get_group_loan_accounts, name="get_group_loan_accounts"),
    url(r'^loanaccounts/member$', get_member_loan_accounts, name="get_member_loan_accounts"),
    url(r'^getmemberfixeddepositaccounts/$', GetFixedDepositAccountsView.as_view(), name="getmemberfixeddepositaccounts"),
    url(r'^getmemberrecurringdepositaccounts/$', GetRecurringDepositAccountsView.as_view(), name="getmemberrecurringdepositaccounts"),
    url(r'^getmemberdepositaccounts/$', ClientDepositAccountsView.as_view(), name="getmemberdepositaccounts"),
    url(r'^getmemberfixeddepositpaidaccounts/$', GetFixedDepositPaidAccountsView.as_view(), name="getmemberfixeddepositpaidaccounts"),
    url(r'^getmemberrecurringdepositpaidaccounts/$', GetRecurringDepositPaidAccountsView.as_view(), name="getmemberrecurringdepositpaidaccounts"),
]

micro_admin/urls.py
from django.conf.urls import url
from micro_admin.views import *

urlpatterns = [

    url(r'^$', IndexView.as_view(), name='microadmin_index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    # ------------------------------------------- #
    # Branch model urls
    url(r'^branch/create/$', CreateBranchView.as_view(), name='createbranch'),
    url(r'^branch/edit/(?P<pk>\d+)/$', UpdateBranchView.as_view(), name='editbranch'),
    url(r'^branch/view/$', BranchListView.as_view(), name='viewbranch'),
    url(r'^branch/delete/(?P<pk>\d+)/$', BranchInactiveView.as_view(), name='deletebranch'),
    url(r'^branch/profile/(?P<pk>\d+)/$', BranchProfileView.as_view(), name='branchprofile'),
    # ------------------------------------------- #
    # User model urls
    url(r'^user/edit/(?P<pk>\d+)/$', UpdateUserView.as_view(), name='edituser'),
    url(r'^user/create/$', CreateUserView.as_view(), name='createuser'),
    url(r'^user/profile/(?P<pk>\d+)/$', UserProfileView.as_view(), name='userprofile'),
    url(r'^users/list/$', UsersListView.as_view(), name='userslist'),
    url(r'^user/delete/(?P<pk>\d+)/$', UserInactiveView.as_view(), name='deleteuser'),
    # ------------------------------------------- #
    # Client model urls
    url(r'^client/create/$', CreateClientView.as_view(), name='createclient'),
    url(r'^client/edit/(?P<pk>\d+)/$', UpdateClientView.as_view(), name='editclient'),
    url(r'^clients/list/$', ClientsListView.as_view(), name='viewclient'),
    url(r'^client/profile/(?P<pk>\d+)/$', ClienProfileView.as_view(), name='clientprofile'),
    url(r'^client/delete/(?P<pk>\d+)/$', ClientInactiveView.as_view(), name='deleteclient'),
    url(r'^client/profile/update/(?P<client_id>\d+)/$', update_clientprofile, name='updateclientprofile'),
    # ------------------------------------------- #
    # Group
    url(r'^group/create/$', CreateGroupView.as_view(), name='creategroup'),
    url(r'^group/(?P<group_id>\d+)/profile/$', GroupProfileView.as_view(), name='groupprofile'),
    url(r'^groups/list/$', GroupsListView.as_view(), name='groupslist'),
    url(r'^group/(?P<group_id>\d+)/delete/$', GroupInactiveView.as_view(), name='deletegroup'),

    # Group - Assign Staff
    url(r'^group/(?P<group_id>\d+)/assign-staff/$', GroupAssignStaffView.as_view(), name='assignstaff'),

    # Group Members (add, remove, view)
    url(r'^group/(?P<group_id>\d+)/members/add/$', GroupAddMembersView.as_view(), name='addmember'),
    url(r'^group/(?P<group_id>\d+)/members/list/$', GroupMembersListView.as_view(), name='viewmembers'),
    url(r'^group/(?P<group_id>\d+)/member/(?P<client_id>\d+)/remove/$', GroupRemoveMembersView.as_view(), name='removemember'),

    # Group Meeting (list, add)
    url(r'^group/(?P<group_id>\d+)/meetings/list/$', GroupMeetingsListView.as_view(), name='groupmeetings'),
    url(r'^group/(?P<group_id>\d+)/meetings/add/$', GroupMeetingsAddView.as_view(), name='addgroupmeeting'),

    # Receipts(create, list)
    url(r'^receiptsdeposit/$', receipts_deposit, name="receiptsdeposit"),
    url(r'^receiptslist/$', ReceiptsList.as_view(), name="receiptslist"),

    url(r'^generalledger/$', GeneralLedger.as_view(), name="generalledger"),
    url(r'^fixeddeposits/$', FixedDepositsView.as_view(), name="fixeddeposits"),
    url(r'^clientfixeddepositsprofile/(?P<fixed_deposit_id>\d+)/$', ClientFixedDepositsProfile.as_view(), name="clientfixeddepositsprofile"),
    url(r'^viewclientfixeddeposits/$', ViewClientFixedDeposits.as_view(), name="viewclientfixeddeposits"),

    # Day Book
    url(r'^viewdaybook/$', DayBookView.as_view(), name="viewdaybook"),
    url(r'^viewparticularclientfixeddeposits/(?P<client_id>\d+)/$', ViewParticularClientFixedDeposits.as_view(), name="viewparticularclientfixeddeposits"),
    url(r'^payslip/$', pay_slip, name="payslip"),
    url(r'^paymentslist/$', PaymentsList.as_view(), name="paymentslist"),
    url(r'^recurringdeposits/$', RecurringDepositsView.as_view(), name="recurringdeposits"),
    url(r'^clientrecurringdepositsprofile/(?P<recurring_deposit_id>\d+)/$', ClientRecurringDepositsProfile.as_view(), name="clientrecurringdepositsprofile"),
    url(r'^viewclientrecurringdeposits/$', ViewClientRecurringDeposits.as_view(), name="viewclientrecurringdeposits"),
    url(r'^viewparticularclientrecurringdeposits/(?P<client_id>\d+)/$', ViewParticularClientRecurringDeposits.as_view(), name="viewparticularclientrecurringdeposits"),
    url(r'^generalledgerpdfdownload/$', GeneralLedgerPdfDownload.as_view(), name="generalledgerpdfdownload"),
    url(r'^daybookpdfdownload/(?P<date>\d{4}-\d{2}-\d{2})/$', DayBookPdfDownload.as_view(), name="daybookpdfdownload"),
    url(r'^userchangepassword/$', UserChangePassword.as_view(), name="userchangepassword"),
    url(r'^getmemberloanaccounts/$', getmember_loanaccounts, name="getmemberloanaccounts"),
    url(r'^getloandemands/$', getloan_demands, name="getloandemands"),
]

microfinance/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^', include('micro_admin.urls', namespace='micro_admin')),
    url(r'^', include('savings.urls', namespace='savings')),
    url(r'^', include('loans.urls', namespace='loans')),
    url(r'^finance/', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

templates/base.html
{% load compress %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>MicroFinance</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.min.css" />
    <link href='http://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' type='text/css'>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/themes/start/jquery-ui.css" />
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
    <!-- your style sheet-->
    {% compress css %}
      <link type="text/css" rel="stylesheet" href="/static/css/mf.css" />
      <link type="text/css" rel="stylesheet" href="/static/css/mf_res.css" />
      <link type="text/css" rel="stylesheet" href="/static/css/mf_mob.css" />
    {% endcompress %}
    <!--your style sheet-->
  </head>
  <body>
    <!--wrapper starts below-->
    <div class="wrapper">
      <!--container starts  below-->
      <div class="container">
        <!--slide-menu-->
        <div class="menu-outer">
          <div class="menu-icon">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
          </div>
        </div>
        <a class="menu-close" onClick="return true">
          <div class="menu-icon">
            <div class="bar"></div>
            <div class="bar"></div>
          </div>
        </a>
        <!--slide menu ends above-->
      </div>
      <!--container ends above-->
      <!--nav bar starts below-->
      <header>
        <div class="container">
          <!--nav bar-->
          <div class="menuu">
            <div class="bs-example box-menu">
              <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header" id="nav-md">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <span class="logo-span">
                      <a class="navbar-brand logo_nav" href="/">
                        <h5>Micro Finance</h5>
                      </a>
                    </span>
                  </div>
                  <!-- Collect the nav links, forms, and other content for toggling -->
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="col-lg-10 col-sm-12 col-md-12 nav navbar-nav navbar-right">
                      <li><a href="{% url 'micro_admin:login' %}" class="menu-link home"><i class="fa fa-home padd"></i>Home</a></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-sitemap padd"></i>Branch
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="{% url 'micro_admin:createbranch' %}"><i class="fa fa-plus padd"></i>Create Branch</a></li>
                          <li><a href="{% url 'micro_admin:viewbranch' %}"><i class="fa fa-eye padd"></i>View Branch</a>
                          </li>
                        </ul>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user padd"></i>Staff
                        <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="{% url 'micro_admin:createuser' %}"><i class="fa fa-plus padd"></i>Create Staff</a>
                          </li>
                          <li><a href="{% url 'micro_admin:userslist' %}"><i class="fa fa-eye padd"></i>View Staff</a></li>
                        </ul>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-users users-icon padd"></i>Group <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="{% url 'micro_admin:creategroup' %}"><i class="fa fa-plus padd"></i>Create Group</a></li>
                          <li><a href="{% url 'micro_admin:groupslist' %}"><i class="fa fa-eye padd"></i>View Group</a>
                          </li>
                        </ul>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-child mem-icon padd"></i>Member <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="{% url 'micro_admin:createclient' %}"><i class="fa fa-plus padd"></i>Create Member</a></li>
                          <li><a href="{% url 'micro_admin:viewclient' %}"><i class="fa fa-eye padd"></i>View Member</a>
                          </li>
                        </ul>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-calculator padd"></i>Accounting <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="{% url 'micro_admin:receiptslist' %}"><i class="fa fa-file-text-o padd"></i>Receipts</a></li>
                          <li><a href="{% url 'micro_admin:paymentslist' %}"><i class="fa fa-money padd"></i>Payments</a></li>
                        </ul>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-money padd"></i>Deposits<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="{% url 'micro_admin:viewclientfixeddeposits' %}"><i class="fa fa-eye padd"></i>View Fixed Deposits</a></li>
                          <li><a href="{% url 'micro_admin:viewclientrecurringdeposits' %}"><i class="fa fa-eye padd"></i>View Recurring Deposits </a></li>
                        </ul>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-file-text-o padd"></i>Reports <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="{% url 'micro_admin:generalledger' %}"><i class="fa fa-calculator padd"></i>General Ledger</a></li>
                          <li><a href="{% url 'micro_admin:viewdaybook' %}"><i class="fa fa-book padd"></i>Day Book</a></li>
                        </ul>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user icon padd"></i>{{ request.user.username|capfirst }} <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="{% url 'micro_admin:userprofile' request.user.id %}"><i class="fa fa-user icon padd"></i>Profile</a></li>
                          <li><a href="{% url 'micro_admin:userchangepassword'%}">
                            <i class="fa fa-unlock-alt padd"></i>Change Password</a>
                          </li>
                          <li><a href="{% url 'micro_admin:logout' %}"><i class="fa fa-power-off icon padd"></i>Logout</a></li>
                        </ul>
                      </li>
                    </ul>
                  </div>
                  <!-- /.navbar-collapse -->
                </div>
                <!-- /.container-fluid -->
              </nav>
            </div>
          </div>
          <!--nav bar ends-->
        </div>
        <!--nav bar ends above-->
      </header>
      {% block basebreadcrumb %}
      <div class="row marl bread-row">
        <div class="breadcrumbcontainer">
          <ol class="breadcrumb">
            <span>You are Here:</span> &nbsp;&nbsp;
            <li><a href="{% url 'micro_admin:login' %}">Home</a></li>
            {% block breadcrumb %}
            {% endblock %}
          </ol>
        </div>
      </div>
      {% endblock basebreadcrumb %}
      <!--content goes below-->
      {% block stage %}
      {% endblock %}
      <!--content ends above-->
    </div>
    <!--wrapper ends above-->
    {% compress js %}
      <script src="/static/js/mf_script.js"></script>
    {% endcompress %}
  </body>
</html>

templates/day_book.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li>Reports</li>
<li>Day Book</li>
{% endblock %}
{% block stage %}
<!--Date Picker Block goes below-->
<div class="container" style="width:97%;">
<div id="dat-txt-box">
  <form id="daybookform" class="form-horizontal" role="form" method="post" action="{% url 'micro_admin:viewdaybook' %}">
    {% csrf_token %}
    <div class="form-group">
      <input type="text" name="date" value="{{date_formated}}" id="datepicker" />
      <button class="submit-btn" type="submit"><i class="fa fa-check padd"></i>Submit</button>
    </div>
  </form>
</div>
</div>
<br clear="all">
<!--Date Picker Block ends above-->
<!--content goes below-->
<div id="day-book-panel" class="container" style ="width:100%">
  <!--form div starts below-->
  <div class="panel panel-default my-panel-bprofile margin-top-set">
    <div class="panel-heading">
    {% if error_message %}
      <div class="alert alert-danger">
        <p>{{ error_message }}</p>
      </div>
    {% else %}
      <h3 class="panel-title">
        Day Book
        <span><a href="{% url 'micro_admin:daybookpdfdownload' selected_date %}" target="_blank"><button class="view-tab-btn"><i class="fa fa-download padd"></i>PDF Download</button></a></span>
      </h3>
    </div>
    {% include "daybook_table.html" %}
    {% endif %}
  </div>
  <!--form div ends above-->
</div>
<!--content ends above-->
{% endblock %}

templates/generalledger.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li>Reports</li>
<li>General Ledger</li>
{% endblock %}
{% block stage %}
<!--content goes below-->
<div class="container-trans-table">
  <!--form div starts below-->
  <div class="panel panel-default my-panel-bprofile margin-top-set trans-table">
    <div class="panel-heading">
      <h3 class="panel-title">
        General Ledger
        <span><a href="{% url 'micro_admin:generalledgerpdfdownload' %}" target="_blank"><button class="view-tab-btn"><i class="fa fa-download padd"></i>PDF Download</button></a></span>
      </h3>
    </div>
    {% include "generalledgertable.html" %}
  </div>
  <!--form div ends above-->
</div>
<!--content ends above-->
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block stage %}
<h4 align="center">
  Welcome {{user.username}}
</h4>
{% endblock %}

templates/list_of_payments.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li>Accounting</li>
<li>Payments</li>
{% endblock %}
{% block stage %}
<!--content goes below-->
<div class="container-trans-table">
  <!--form div starts below-->
  <div class="panel panel-default my-panel-bprofile margin-top-set trans-table">
    <div class="panel-heading">
      <h3 class="panel-title">
        Payments Lists
        <span><a href="{% url 'micro_admin:payslip' %}"><button class="ed-btn"><i class="fa fa-plus padd"></i>New Payment
        </button>
        </a></span>
      </h3>
    </div>
    <div class="hg-table panel-body pb-table">
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr class="head-row-tb">
              <th>S.No.</th>
              <th>Date</th>
              <th>Vocher Number</th>
              <th>Group Name</th>
              <th>Member Name</th>
              <th>Staff Name</th>
              <th>Payment Type</th>
              <th>Amount</th>
              <th>Interest</th>
              <th>Total Amount</th>
            </tr>
          </thead>
          <tbody class="body-row-tb">
            {% for payment in payments_list %}
            <tr>
              <td><b>{{ forloop.counter }}</b></td>
              <td>{{ payment.date }}</td>
              <td>{{ payment.voucher_number}}</td>
              <td>
              {% if payment.group %}
              <a href="{% url 'micro_admin:groupprofile' payment.group.id %}" style="color:#337ab7;">
              {% endif %}
              {{ payment.group.name|capfirst|default:" - " }}
              {% if payment.group %}</a>{% endif %}
              </td>
              <td>
              {% if payment.client %}
                <a href="{% url 'micro_admin:clientprofile' payment.client.id %}" style="color:#337ab7;">
              {% endif %}
              {{ payment.client.first_name|capfirst|default:" - " }}
              {% if payment.client %}</a>{% endif %}
              </td>
              <td>
              {% if payment.staff %}
                <a href="{% url 'micro_admin:userprofile' payment.staff.id %}" style="color:#337ab7;">
              {% endif %}
              {{ payment.staff.username|capfirst|default:" - " }}
              {% if payment.staff %}</a>{% endif %}
              </td>
              <td>{{ payment.payment_type }}</td>
              <td>{{ payment.amount|floatformat:2 }}</td>
              <td>{% if payment.interest %}{{ payment.interest|default:" - " }}{% else %}-{% endif %}</td>
              <td style="color:#FF00CC;">{{ payment.total_amount|floatformat:2 }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!--form div ends above-->
</div>
<!--content ends above-->
{% endblock %}

templates/listof_receipts.html
{% extends 'base.html' %}
{% block breadcrumb %}
<li>Accounting</li>
<li>Receipts</li>
{% endblock %}
{% block stage %}
<!--content goes below-->
<div class="container-trans-table">
  <!--form div starts below-->
  <div class="panel panel-default my-panel-bprofile margin-top-set trans-table">
    <div class="panel-heading">
      <h3 class="panel-title">
        Receipts Lists
        <span><a href="{% url 'micro_admin:receiptsdeposit' %}"><button class="ed-btn"><i class="fa fa-plus padd"></i>New Receipt</button>
        </a></span>
      </h3>
    </div>
    <div class="hg-table panel-body pb-table">
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
            <tr class="head-row-tb">
              <th class="wid-10">S.No.</th>
              <th class="wid-90">Date</th>
              <th class="wid-10">Receipt Number</th>
              <th>Member Name</th>
              <th class="wid-10">Share Capital</th>
              <th class="wid-10">Entrance Fee</th>
              <th class="wid-10">Membership Fee</th>
              <th class="wid-10">Book Fee</th>
              <th class="wid-74">Loan Processing Fee</th>
              <th class="wid-90">Thrift Deposits</th>
              <th>Fixed Deposit Account</th>
              <th class="wid-90">Fixed Deposits</th>
              <th>Recurring Deposit Account</th>
              <th class="wid-90">Recurring Deposits</th>
              <th class="wid-90">Member Loan A/C. No.</th>
              <th class="wid-90">Group Loan A/C. No.</th>
              <th class="wid-90">Loan Principal Amount</th>
              <th class="wid-90">Loan Interest Amount</th>
              <th class="wid-90">Insurance Amount</th>
              <th class="wid-90">Created By</th>
            </tr>
          </thead>
          <tbody class="body-row-tb">
            {% for receipt in receipt_list %}
            <tr>
              <td><b>{{ forloop.counter }}</b></td>
              <td>{{ receipt.date }}</td>
              <td>{{ receipt.receipt_number}}</td>
              <td><a href="{% url 'micro_admin:clientprofile' receipt.client.id %}" style="color:#337ab7;">{{ receipt.client.first_name|capfirst }} {{ receipt.client.last_name|capfirst }}</a></td>
              <td>
                {% if receipt.sharecapital_amount%}{{ receipt.sharecapital_amount|floatformat:2}}{% else %}-{% endif %}
              </td>
              <td>
                {% if receipt.entrancefee_amount%}{{ receipt.entrancefee_amount|floatformat:2 }}{% else %}-{% endif %}
              </td>
              <td>
                {% if receipt.membershipfee_amount%}{{ receipt.membershipfee_amount|floatformat:2 }}{% else %}-{% endif %}
              </td>
              <td>
                {% if receipt.bookfee_amount%}{{ receipt.bookfee_amount|floatformat:2}}{% else %}-{% endif %}
              </td>
              <td>
                {% if receipt.loanprocessingfee_amount%}{{ receipt.loanprocessingfee_amount|floatformat:2 }}
                {% else %}-{% endif %}
              </td>
              <td>
                {% if receipt.savingsdeposit_thrift_amount%}{{ receipt.savingsdeposit_thrift_amount|floatformat:2 }}
                {% else %}-{% endif %}
              </td>
              <td>
                {% if receipt.fixed_deposit_account %}
                  <a href="{% url 'micro_admin:clientfixeddepositsprofile' receipt.fixed_deposit_account.id %}" style="color:#337ab7;">{{ receipt.fixed_deposit_account.fixed_deposit_number }}</a>
                  {% else %}-{% endif %}
              </td>
              <td>
                {% if receipt.fixeddeposit_amount%}{{ receipt.fixeddeposit_amount|floatformat:2 }}{% else %}-{% endif %}
              </td>
              <td>
                {% if receipt.recurring_deposit_account %}
                  <a href="{% url 'micro_admin:clientrecurringdepositsprofile' receipt.recurring_deposit_account.id %}" style="color:#337ab7;">{{ receipt.recurring_deposit_account.reccuring_deposit_number }}</a>
                {% else %}-{% endif %}
              </td>
              <td>
                {% if receipt.recurringdeposit_amount%}{{ receipt.recurringdeposit_amount|floatformat:2 }}{% else %}-{% endif %}
              </td>
              <td>
                {{ receipt.member_loan_account.account_no|default:" - " }}
              </td>
              <td>
                {{ receipt.group_loan_account.account_no|default:" - " }}
              </td>
              <td>
                {% if receipt.loanprinciple_amount%}{{ receipt.loanprinciple_amount|floatformat:2 }}{% else %}-{% endif %}
              </td>
              <td>
                {% if receipt.loaninterest_amount%}{{ receipt.loaninterest_amount|floatformat:2}}{% else %}-{% endif %}
              </td>
              <td>
                {% if receipt.insurance_amount%}{{ receipt.insurance_amount|floatformat:2 }}{% else %}-{% endif %}
              </td>
              <td>
                <a href="{% url 'micro_admin:userprofile' receipt.staff.id %}" style="color:#337ab7;">{{ receipt.staff|capfirst|default:" - " }}</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!--form div ends above-->
</div>
<!--content ends above-->
{% endblock %}