core/urls.py
from django.conf.urls import url
from core.views import Receipts_Deposit, ClientLoanAccountsView, GetLoanDemandsView, PaySlipCreateView, get_group_loan_accounts, \
	get_member_loan_accounts, GetFixedDepositAccountsView, GetRecurringDepositAccountsView, ClientDepositAccountsView, \
	GetFixedDepositPaidAccountsView, GetRecurringDepositPaidAccountsView

urlpatterns = [
    url(r'^receiptsdeposit/$', Receipts_Deposit.as_view(), name="receiptsdeposit"),
    url(r'^getmemberloanaccounts/$', ClientLoanAccountsView.as_view(), name="receiptsdeposit"),
    url(r'^getloandemands/$', GetLoanDemandsView.as_view(), name="getloandemands"),
    url(r'^payslip/$', PaySlipCreateView.as_view(), name="payslip"),
    url(r'^loanaccounts/group$', get_group_loan_accounts, name="get_group_loan_accounts"),
    url(r'^loanaccounts/member$', get_member_loan_accounts, name="get_member_loan_accounts"),
    url(r'^getmemberfixeddepositaccounts/$', GetFixedDepositAccountsView.as_view(), name="getmemberfixeddepositaccounts"),
    url(r'^getmemberrecurringdepositaccounts/$', GetRecurringDepositAccountsView.as_view(), name="getmemberrecurringdepositaccounts"),
    url(r'^getmemberdepositaccounts/$', ClientDepositAccountsView.as_view(), name="getmemberdepositaccounts"),
    url(r'^getmemberfixeddepositpaidaccounts/$', GetFixedDepositPaidAccountsView.as_view(), name="getmemberfixeddepositpaidaccounts"),
    url(r'^getmemberrecurringdepositpaidaccounts/$', GetRecurringDepositPaidAccountsView.as_view(), name="getmemberrecurringdepositpaidaccounts"),
]

loans/urls.py
from django.conf.urls import url
from loans.views import *

urlpatterns = [
    # Client Loans (apply, view, list)
    url(r'^client/(?P<client_id>\d+)/loan/apply/$', ClientLoanApplicationView.as_view(), name='clientloanapplication'),
    url(r'^client/(?P<client_id>\d+)/loans/list/$', ClientLoansListView.as_view(), name="clientloanaccountslist"),
    url(r'^client/loan/(?P<pk>\d+)/view/$', ClientLoanAccount.as_view(), name='clientloanaccount'),
    url(r'^client/(?P<client_id>\d+)/loan/(?P<loanaccount_id>\d+)/deposits/list/$', ClientLoanDepositsListView.as_view(), name='listofclientloandeposits'),

    # Client Loans - Ledger (view, CSV, Excel, PDF downloads)
    url(r'^client/(?P<client_id>\d+)/loan/(?P<loanaccount_id>\d+)/ledger/$', ClientLoanLedgerView.as_view(), name="clientloanledgeraccount"),
    url(r'^client/(?P<client_id>\d+)/loan/(?P<loanaccount_id>\d+)/ledger/download/csv/$', ClientLedgerCSVDownload.as_view(), name="clientledgercsvdownload"),
    url(r'^client/(?P<client_id>\d+)/loan/(?P<loanaccount_id>\d+)/ledger/download/excel/$', ClientLedgerExcelDownload.as_view(), name="clientledgerexceldownload"),
    url(r'^client/(?P<client_id>\d+)/loan/(?P<loanaccount_id>\d+)/ledger/download/pdf/$', ClientLedgerPDFDownload.as_view(), name="clientledgerpdfdownload"),

    # Group Loans (apply, view, list)
    url(r'^group/(?P<group_id>\d+)/loan/apply/$', GroupLoanApplicationView.as_view(), name='grouploanapplication'),
    url(r'^group/(?P<group_id>\d+)/loans/list/$', GroupLoansListView.as_view(), name="grouploanaccountslist"),
    url(r'^group/loan/(?P<pk>\d+)/view/$', GroupLoanAccount.as_view(), name='grouploanaccount'),
    url(r'^group/(?P<group_id>\d+)/loan/(?P<loanaccount_id>\d+)/deposits/list/$', GroupLoanDepositsListView.as_view(), name='viewgrouploandeposits'),

    # Change Loan Account Status
    url(r'^loan/(?P<pk>\d+)/change-status/$', ChangeLoanAccountStatus.as_view(), name='change_loan_account_status'),

    # Issue Loan
    url(r'^loan/(?P<loanaccount_id>\d+)/issue/$', IssueLoan.as_view(), name='issueloan'),
]

micro_admin/urls.py
from django.conf.urls import url
from micro_admin.views import *

urlpatterns = [

    url(r'^$', IndexView.as_view(), name='microadmin_index'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    # ------------------------------------------- #
    # Branch model urls
    url(r'^branch/create/$', CreateBranchView.as_view(), name='createbranch'),
    url(r'^branch/edit/(?P<pk>\d+)/$', UpdateBranchView.as_view(), name='editbranch'),
    url(r'^branch/view/$', BranchListView.as_view(), name='viewbranch'),
    url(r'^branch/delete/(?P<pk>\d+)/$', BranchInactiveView.as_view(), name='deletebranch'),
    url(r'^branch/profile/(?P<pk>\d+)/$', BranchProfileView.as_view(), name='branchprofile'),
    # ------------------------------------------- #
    # User model urls
    url(r'^user/edit/(?P<pk>\d+)/$', UpdateUserView.as_view(), name='edituser'),
    url(r'^user/create/$', CreateUserView.as_view(), name='createuser'),
    url(r'^user/profile/(?P<pk>\d+)/$', UserProfileView.as_view(), name='userprofile'),
    url(r'^users/list/$', UsersListView.as_view(), name='userslist'),
    url(r'^user/delete/(?P<pk>\d+)/$', UserInactiveView.as_view(), name='deleteuser'),
    # ------------------------------------------- #
    # Client model urls
    url(r'^client/create/$', CreateClientView.as_view(), name='createclient'),
    url(r'^client/edit/(?P<pk>\d+)/$', UpdateClientView.as_view(), name='editclient'),
    url(r'^clients/list/$', ClientsListView.as_view(), name='viewclient'),
    url(r'^client/profile/(?P<pk>\d+)/$', ClienProfileView.as_view(), name='clientprofile'),
    url(r'^client/delete/(?P<pk>\d+)/$', ClientInactiveView.as_view(), name='deleteclient'),
    url(r'^client/profile/update/(?P<client_id>\d+)/$', update_clientprofile, name='updateclientprofile'),
    # ------------------------------------------- #
    # Group
    url(r'^group/create/$', CreateGroupView.as_view(), name='creategroup'),
    url(r'^group/(?P<group_id>\d+)/profile/$', GroupProfileView.as_view(), name='groupprofile'),
    url(r'^groups/list/$', GroupsListView.as_view(), name='groupslist'),
    url(r'^group/(?P<group_id>\d+)/delete/$', GroupInactiveView.as_view(), name='deletegroup'),

    # Group - Assign Staff
    url(r'^group/(?P<group_id>\d+)/assign-staff/$', GroupAssignStaffView.as_view(), name='assignstaff'),

    # Group Members (add, remove, view)
    url(r'^group/(?P<group_id>\d+)/members/add/$', GroupAddMembersView.as_view(), name='addmember'),
    url(r'^group/(?P<group_id>\d+)/members/list/$', GroupMembersListView.as_view(), name='viewmembers'),
    url(r'^group/(?P<group_id>\d+)/member/(?P<client_id>\d+)/remove/$', GroupRemoveMembersView.as_view(), name='removemember'),

    # Group Meeting (list, add)
    url(r'^group/(?P<group_id>\d+)/meetings/list/$', GroupMeetingsListView.as_view(), name='groupmeetings'),
    url(r'^group/(?P<group_id>\d+)/meetings/add/$', GroupMeetingsAddView.as_view(), name='addgroupmeeting'),

    # Receipts(create, list)
    url(r'^receiptsdeposit/$', receipts_deposit, name="receiptsdeposit"),
    url(r'^receiptslist/$', ReceiptsList.as_view(), name="receiptslist"),

    url(r'^generalledger/$', GeneralLedger.as_view(), name="generalledger"),
    url(r'^fixeddeposits/$', FixedDepositsView.as_view(), name="fixeddeposits"),
    url(r'^clientfixeddepositsprofile/(?P<fixed_deposit_id>\d+)/$', ClientFixedDepositsProfile.as_view(), name="clientfixeddepositsprofile"),
    url(r'^viewclientfixeddeposits/$', ViewClientFixedDeposits.as_view(), name="viewclientfixeddeposits"),

    # Day Book
    url(r'^viewdaybook/$', DayBookView.as_view(), name="viewdaybook"),
    url(r'^viewparticularclientfixeddeposits/(?P<client_id>\d+)/$', ViewParticularClientFixedDeposits.as_view(), name="viewparticularclientfixeddeposits"),
    url(r'^payslip/$', pay_slip, name="payslip"),
    url(r'^paymentslist/$', PaymentsList.as_view(), name="paymentslist"),
    url(r'^recurringdeposits/$', RecurringDepositsView.as_view(), name="recurringdeposits"),
    url(r'^clientrecurringdepositsprofile/(?P<recurring_deposit_id>\d+)/$', ClientRecurringDepositsProfile.as_view(), name="clientrecurringdepositsprofile"),
    url(r'^viewclientrecurringdeposits/$', ViewClientRecurringDeposits.as_view(), name="viewclientrecurringdeposits"),
    url(r'^viewparticularclientrecurringdeposits/(?P<client_id>\d+)/$', ViewParticularClientRecurringDeposits.as_view(), name="viewparticularclientrecurringdeposits"),
    url(r'^generalledgerpdfdownload/$', GeneralLedgerPdfDownload.as_view(), name="generalledgerpdfdownload"),
    url(r'^daybookpdfdownload/(?P<date>\d{4}-\d{2}-\d{2})/$', DayBookPdfDownload.as_view(), name="daybookpdfdownload"),
    url(r'^userchangepassword/$', UserChangePassword.as_view(), name="userchangepassword"),
    url(r'^getmemberloanaccounts/$', getmember_loanaccounts, name="getmemberloanaccounts"),
    url(r'^getloandemands/$', getloan_demands, name="getloandemands"),
]

microfinance/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^', include('micro_admin.urls', namespace='micro_admin')),
    url(r'^', include('savings.urls', namespace='savings')),
    url(r'^', include('loans.urls', namespace='loans')),
    url(r'^finance/', include('core.urls', namespace='core')),
    url(r'^admin/', include(admin.site.urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

templates/group/loan/account.html
{% extends 'group/groupbase.html' %}
{% block groupbreadcrumb %}
<li><a href="{% url 'loans:grouploanaccountslist' group.id %}">Loans</a></li>
<li>Loan Account - {{ loan_account.account_no }}</li>
{% endblock %}
{% block groupstage %}
<div class="home-div-gp">
<div class="wrap-cp-div">
  {% if user.is_admin or user.user_roles == "BranchManager" %}
  <div class="btn-row">
    {% if loan_account.status == "Withdrawn" %}
    <a title="Account has already been Withdrawn"><button><i class="fa fa-arrow-circle-o-down padd"></i>Withdrawn</button></a>
    {% else %}
    <a class='change-account-status' data-href="{% url 'loans:change_loan_account_status' loan_account.id %}?status=Withdrawn"><button id="withdraw-button"><i class="fa fa-arrow-circle-o-down padd"></i>Withdraw</button></a>
    {% endif %}
    {% if loan_account.status == "Approved" %}
    <a title="Account has already been Approved"><button><i class="fa fa-check-circle-o padd"></i>Approved</button></a>
    {% else %}
    <a class='change-account-status' data-href="{% url 'loans:change_loan_account_status' loan_account.id %}?status=Approved"><button id="approve-button"><i class="fa fa-check-circle-o padd"></i>Approve</button></a>
    {% endif %}
    {% if loan_account.status == "Rejected" %}
    <a title="Account has already been Rejected"><button><i class="fa fa-times-circle-o padd"></i>Rejected</button></a>
    {% else %}
    <a class='change-account-status' data-href="{% url 'loans:change_loan_account_status' loan_account.id %}?status=Rejected"><button id="reject-button"><i class="fa fa-times-circle-o padd"></i>Reject</button></a>
    {% endif %}
    {% if loan_account.status == "Closed" %}
    <a title="Account has already been Closed"><button><i class="fa fa-trash-o padd"></i>Closed</button></a>
    {% else %}
    <a class='change-account-status' data-href="{% url 'loans:change_loan_account_status' loan_account.id %}?status=Closed"><button id="close-button"><i class="fa fa-trash-o padd"></i>Close</button></a>
    {% endif %}
    <br clear="all" />
  </div>
  {% endif %}
</div>
<div class="panel panel-default panel-hdg">
<div class="panel-heading min-ht-res-60">
  <h3 class="panel-title">
    {% if group.is_active %}<i class="fa fa-square green padd"></i>{% else %}<i class="fa fa-square red padd"></i>{% endif %}
    {{ group.name|capfirst }} Loan Account</h3>
    <span class="mar-tp-m"><a href="{% url 'loans:viewgrouploandeposits' group.id loan_account.id %}" class="view-tab-btn"><i class="fa fa-eye padd"></i>View Loan Deposits</a>
    {% if user.is_admin == 0 and user.user_roles != "BranchManager" %}
      {% if loan_account.status == "Withdrawn" %}
      <a title="Account has already been Withdrawn" class="view-tab-btn ed-btn"><i class="fa fa-arrow-circle-o-down padd"></i>Withdrawn</a>
      {% else %}
      <a data-href="{% url 'loans:change_loan_account_status' loan_account.id %}?status=Withdrawn" class="view-tab-btn ed-btn change-account-status" id="withdraw-button"><i class="fa fa-arrow-circle-o-down padd"></i>Withdraw</a>
      {% endif %}
    {% endif %}
  </span>
</div>
<div class="panel-body">
  <!--panel body starts above-->
  <form id="grouploanaccountform" class="form-horizontal" role="form">
    {% csrf_token %}
    <!--div 1 0f form-->
    <div class="box-form">
      <div class="form-group grp-view">
        <input type="hidden"  id="loanaccount_id" value="{{ loan_account.id }}" style="dispaly:none;">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Loan A/C Number :</label><span class="col-lg-6 mar-top">{{ loan_account.account_no }}</span>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Applied By Staff :</label><span class="col-lg-6 mar-top"><a href="{% url 'micro_admin:userprofile' loan_account.created_by.id %}">{{ loan_account.created_by|capfirst }}
        </a></span>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Loan Issued By :</label><span class="col-lg-6 mar-top">{{ loan_account.loan_issued_by|capfirst }}</span>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Loan Amount :</label><span class="col-lg-6 mar-top" style="color:#FF00CC;">{{ loan_account.loan_amount }}</span>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Loan Period :</label><span class="col-lg-6 mar-top">{{ loan_account.loan_repayment_period }} Months</span>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Total Principle Repaid Amount :</label><span class="col-lg-6 mar-top" style="color:#337ab7;">{{ loan_account.total_loan_amount_repaid }}</span>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Total Repaid Amount :</label><span class="col-lg-6 mar-top" style="color:#337ab7;">{{ loan_account.total_loan_paid }}</span>
      </div>
    </div>
    <!--div 1 of fomr ends above-->
    <!--div 2 of form starts below-->
    <div class="box-form">
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Status :</label>
        {% if loan_account.status == "Applied" %}
        <span class="col-lg-6 mar-top" style="color:#337ab7;">
        {% elif loan_account.status == "Withdrawn" %}
        <span class="col-lg-6 mar-top" style="color:#FF6600;">
        {% elif loan_account.status == "Approved" %}
        <span class="col-lg-6 mar-top" style="color:#008000;">
        {% elif loan_account.status == "Rejected" %}
        <span class="col-lg-6 mar-top red">
        {% elif loan_account.status == "Closed" %}
        <span class="col-lg-6 mar-top" style="color:#660099;">
        {% endif %}
        {{ loan_account.status }} <span style="color:#337ab7;">&nbsp;&nbsp;{% if loan_account.status == "Approved" %} On {{ loan_account.approved_date }}</span></span>{% endif %}
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Applied On :</label><span class="col-lg-6 mar-top">{{ loan_account.opening_date }}</span>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Loan Issued On :</label><span class="col-lg-6 mar-top">
        {{ loan_account.loan_issued_date }}
        {% if user.is_admin and not loan_account.loan_issued_date %}
        <a href="{% url 'loans:issueloan' loan_account.id %}" style="text-decoration:none; color:#fff; margin-left:3px;" title="Issue Loan"><i class="fa fa-pencil-square-o trash-icon"></i></a>
        {% endif %}
        </span>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Annual Interest Rate :</label><span class="col-lg-5 mar-top">{{ loan_account.annual_interest_rate }} % &nbsp;&nbsp; {{ loan_account.interest_type }} Interest</span>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Loan Repayment Every :</label><span class="col-lg-5 mar-top">{{ loan_account.loan_repayment_every }} Month{{ loan_account.loan_repayment_every|pluralize }}</span>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">Total Interset Repaid Amount :</label><span class="col-lg-6 mar-top" style="color:#337ab7;">{{ loan_account.total_interest_repaid }}</span>
      </div>
      <div class="form-group">
        <label for="inputEmail3" class="col-lg-6 col-sm-6 control-label">
        Principle Balance Amount :
        </label>
        <span class="col-lg-5 mar-top" style="color:#337ab7;">{{ loan_account.total_loan_balance }} </span>
      </div>
    </div>
    <br clear="all" />
  </form>
</div>
<!--panel body ends below crct-->
<!--content ends above-->
<script type="text/javascript">
  $(document).ready(function() {
    $('.change-account-status').click(function(e) {
      e.preventDefault();
      submit_url = $(this).attr("data-href")
      $.post(submit_url, $('#grouploanaccountform').serialize(), function(data) {
        if (data.error) {
          alert(data.error_message);
        }
        else {
          alert("Group Loan account status changed successfully.")
          window.location = '.';
        }
      }, "json");
    });
  });
</script>
{% endblock %}

templates/group/loan/application.html
{% extends 'group/groupbase.html' %}
{% block groupbreadcrumb %}
<li>Add Loan Application</li>
{% endblock %}
{% block groupstage %}
<!--content goes below-->
<div class="container">
  <!--form div starts below-->
  <div class="panel panel-default my-panel wid-panel-form margin-top-set">
    <div class="panel-heading">{% if group.is_active %}<i class="fa fa-square green padd"></i>{% else %}<i class="fa fa-square red padd"></i>{% endif %}
      {{ group.name|capfirst }} Loan Application
    </div>
    <div class="panel-body pb-pad">
      <form id="grouploanapplicationform" class="form-horizontal" role="form" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-5 control-label">Account Number</label>
          <div class="col-sm-7">
            <input type="hidden"  id="group_id" value="{{ group.id }}" style="dispaly:none;">
            <input type="text" class="text-box wid-form" name="account_no" value="{{account_no}}" id="account_no">
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-5 control-label">Created By</label>
          <div class="col-sm-7">
            <input type="text" class="text-box wid-form" id="created_by" value="{{ user.username }}" name="created_by" readonly>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-5 control-label">Loan Amount<span>*</span></label>
          <div class="col-sm-7">
            <input type="text" class="text-box wid-form" name="loan_amount" id="loan_amount">
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-5 control-label">Loan Repayment Period (in months)<span>*</span></label>
          <div class="col-sm-7">
            <input type="text" class="text-box wid-form" name="loan_repayment_period" id="loan_repayment_period">
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-5 control-label">Loan Repayment Every (in months)<span>*</span></label>
          <div class="col-sm-7">
            <input type="text" class="text-box wid-form" name="loan_repayment_every" id="loan_repayment_every">
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-5 control-label">Interset Type<span>*</span></label>
          <div class="col-sm-7">
            <select class="text-box wid-form" name="interest_type" id="interest_type" required="True">
              <option>Select Interest Type</option>
              <option value="Flat">Flat</option>
              <option value="Declining">Declining</option>
            </select>
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-5 control-label">Annual Interest Rate (%)<span>*</span></label>
          <div class="col-sm-7">
            <input type="text" class="text-box wid-form" name="annual_interest_rate" id="annual_interest_rate">
          </div>
        </div>
        <div class="form-group">
          <label for="inputEmail3" class="col-sm-5 control-label">Loan Purpose<span>*</span></label>
          <div class="col-sm-7">
            <textarea name="loanpurpose_description" id="loanpurpose_description" rows="3" class="txt-area-wid"></textarea>
          </div>
        </div>
        <div class="form-group btns">
          <button class="submit-btn" type="submit"><i class="fa fa-check padd"></i>Submit</button>
          <button class="cancel-btn" type="reset"><i class="fa fa-times padd"></i>Cancel</button>
        </div>
      </form>
    </div>
  </div>
  <!--form div ends above-->
</div>
<!--content ends above-->
<script type="text/javascript">
  $(document).ready(function() {
    $('#grouploanapplicationform').submit(function(e) {
      e.preventDefault();
      $.post('.', $('#grouploanapplicationform').serialize(), function(data) {
        if (data.error) {
          $("span.error").remove();
          $.each(data.message, function( key, value ) {
            $('#'+key).after("<span class='error' style='height:11px;color:red;'>" + value + "</span>");
          });
        }
        else {
          alert("Group Loan Application submitted sucessfully");
          url = "{% url 'loans:grouploanaccount' 1 %}".replace(1, data.loanaccount_id)
          window.location = url;
        }
      }, "json");
    });
    $('.cancel-btn').click(function(e){
      $("span.error").remove();
    });
  });
</script>
{% endblock %}

templates/group/loan/list_of_loan_deposits.html
{% extends 'group/groupbase.html' %}
{% block groupbreadcrumb %}
<li><a href="{% url 'loans:grouploanaccountslist' loan_account.group.id %}">Loans</a></li>
<li><a href="{% url 'loans:grouploanaccount' loan_account.id %}">Loan Account - {{ loan_account.account_no }}</a></li>
<li>View Loan Deposits</li>
{% endblock %}
{% block groupstage %}
<div class="home-div-gp">
  <div class="panel panel-default panel-hdg">
    <div class="panel-heading min-ht-res-60">
      <h3 class="panel-title">
        {% if group.is_active %}<i class="fa fa-square green padd"></i>{% else %}<i class="fa fa-square red padd"></i>{% endif %}
        {{ group.name|capfirst }} Loan Deposits List</h3>
        <span class="mar-tp-m"><a href="{% url 'loans:grouploanaccount' loan_account.id %}" class="view-tab-btn ed-btn"><i class="fa fa-arrow-circle-left padd"></i>Back</a></span>
    </div>
    <div class="panel-body">
      <!--panel body starts above-->
      <form class="form-horizontal" role="form">
      <!--div 1 0f form-->
      <div class="box-form">
        <div class="form-group">
          <label for="inputEmail3" class="col-lg-6 col-sm-6 col-xs-6 control-label">Number of Deposits :</label><span class="col-lg-6 mar-top"><b>{{ receipts_list.count }}</b></span>
        </div>
      </div>
      <!--div 1 of fomr ends above-->
      <br clear="all" />
      <div class="hg-table">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>S.No</th>
                <th>Receipt No</th>
                <th>Deposited Date</th>
                <th>Member Name</th>
                <th>Demand Principle</th>
                <th>Demand Interest</th>
                <th>Loan Principle</th>
                <th>Loan Interest</th>
                <th>Loan Principal Balance</th>
                <th>Deposit Done By</th>
              </tr>
            </thead>
            <tbody>
              {% for receipt in receipts_list %}
              <tr>
                <td><b>{{ forloop.counter }}</b></td>
                <td>{{ receipt.receipt_number }}</td>
                <td>{{ receipt.date }}</td>
                <td>{{ receipt.client.first_name }}</td>
                <td>{{ receipt.demand_loanprinciple_amount_atinstant|floatformat:2  }}</td>
                <td>{{ receipt.demand_loaninterest_amount_atinstant|floatformat:2  }}</td>
                <td>{{ receipt.loanprinciple_amount|floatformat:2  }}</td>
                <td>{{ receipt.loaninterest_amount }}</td>
                <td style="color:#FF00CC;">{{ receipt.principle_loan_balance_atinstant|floatformat:2  }}</td>
                <td>{{ receipt.staff.username|capfirst }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <!--panel body ends below crct-->
  </div>
</div>
<!--content ends above-->
{% endblock %}